-- ============================================================================
-- NUTRIFY - IMPORT 1346 MAKANAN INDONESIA KE DATABASE
-- ============================================================================
-- Jalankan SQL ini di Supabase SQL Editor
-- Pastikan tabel local_foods sudah ada (dari prisma migrate)
-- ============================================================================

-- Truncate existing data (optional - hapus comment jika mau reset)
-- TRUNCATE TABLE local_foods RESTART IDENTITY CASCADE;

-- Insert all foods from nutrition.csv
INSERT INTO local_foods (id, name, category, origin, calories, protein_g, carbs_g, fat_g, fiber_g, sodium_mg, sugar_g, is_vegetarian, is_vegan, is_halal, benefits, common_preparations, created_at, updated_at)
VALUES
-- Batch 1: Foods 1-100
(gen_random_uuid(), 'Abon', 'proteins', 'Indonesia', 280, 9.2, 0, 28.4, 0.5, 800, 0, false, false, true, ARRAY['Tinggi protein', 'Sumber energi'], ARRAY['Taburan nasi', 'Isian roti'], NOW(), NOW()),
(gen_random_uuid(), 'Abon haruwan', 'proteins', 'Indonesia', 513, 23.7, 21.3, 37, 0.5, 800, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Lauk'], NOW(), NOW()),
(gen_random_uuid(), 'Agar-agar', 'other', 'Indonesia', 0, 0, 0, 0.2, 0.5, 5, 0, true, true, true, ARRAY['Rendah kalori', 'Serat tinggi'], ARRAY['Dessert', 'Puding'], NOW(), NOW()),
(gen_random_uuid(), 'Akar tonjong segar', 'vegetables', 'Indonesia', 45, 1.1, 10.8, 0.4, 1.5, 5, 1, true, true, true, ARRAY['Rendah kalori'], ARRAY['Sayur'], NOW(), NOW()),
(gen_random_uuid(), 'Aletoge segar', 'vegetables', 'Indonesia', 37, 4.4, 3.8, 0.5, 1.5, 5, 0.5, true, true, true, ARRAY['Rendah kalori', 'Sumber protein nabati'], ARRAY['Sayur'], NOW(), NOW()),
(gen_random_uuid(), 'Alpukat segar', 'fruits', 'Indonesia', 85, 0.9, 7.7, 6.5, 2, 5, 0.5, true, true, true, ARRAY['Lemak sehat', 'Sumber vitamin E'], ARRAY['Jus', 'Salad'], NOW(), NOW()),
(gen_random_uuid(), 'Ampas kacang hijau', 'grains', 'Indonesia', 96, 3.7, 19.1, 0.6, 2, 5, 1, true, true, true, ARRAY['Serat tinggi'], ARRAY['Kue'], NOW(), NOW()),
(gen_random_uuid(), 'Ampas Tahu', 'proteins', 'Indonesia', 414, 26.6, 41.3, 18.3, 3, 50, 0, true, true, true, ARRAY['Tinggi protein', 'Serat tinggi'], ARRAY['Perkedel'], NOW(), NOW()),
(gen_random_uuid(), 'Ampas tahu kukus', 'proteins', 'Indonesia', 75, 4.1, 10.7, 2.1, 2, 50, 0, true, true, true, ARRAY['Rendah kalori', 'Protein nabati'], ARRAY['Lauk'], NOW(), NOW()),
(gen_random_uuid(), 'Ampas tahu mentah', 'proteins', 'Indonesia', 67, 5, 8.1, 2.1, 2, 50, 0, true, true, true, ARRAY['Protein nabati'], ARRAY['Olahan'], NOW(), NOW()),
(gen_random_uuid(), 'Anak sapi daging gemuk segar', 'proteins', 'Indonesia', 184, 18.8, 0, 14, 0, 50, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Steak', 'Sop'], NOW(), NOW()),
(gen_random_uuid(), 'Anak sapi daging kurus segar', 'proteins', 'Indonesia', 174, 19.6, 0, 10, 0, 50, 0, false, false, true, ARRAY['Tinggi protein', 'Rendah lemak'], ARRAY['Steak', 'Sop'], NOW(), NOW()),
(gen_random_uuid(), 'Anak sapi daging sedang segar', 'proteins', 'Indonesia', 190, 19.1, 0, 12, 0, 50, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Steak', 'Sop'], NOW(), NOW()),
(gen_random_uuid(), 'Andaliman segar', 'spices', 'Indonesia', 99, 4.6, 18, 1, 3, 10, 1, true, true, true, ARRAY['Antioksidan', 'Bumbu khas Batak'], ARRAY['Bumbu masakan'], NOW(), NOW()),
(gen_random_uuid(), 'Andewi', 'vegetables', 'Indonesia', 25, 1.6, 5.3, 0.2, 1.5, 5, 0.5, true, true, true, ARRAY['Rendah kalori', 'Serat tinggi'], ARRAY['Salad', 'Lalapan'], NOW(), NOW()),
(gen_random_uuid(), 'Anggur hutan segar', 'fruits', 'Indonesia', 30, 0.5, 6.8, 0.2, 0.8, 5, 5, true, true, true, ARRAY['Antioksidan'], ARRAY['Dimakan langsung'], NOW(), NOW()),
(gen_random_uuid(), 'Angsa', 'proteins', 'Indonesia', 354, 16.4, 0, 31.5, 0, 50, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Panggang', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Anyang sayur', 'prepared_dishes', 'Indonesia', 126, 3.4, 10.3, 7.9, 2, 400, 2, true, true, true, ARRAY['Sayuran sehat'], ARRAY['Lauk'], NOW(), NOW()),
(gen_random_uuid(), 'Apel', 'fruits', 'Indonesia', 58, 0.3, 14.9, 0.4, 2, 5, 10, true, true, true, ARRAY['Serat tinggi', 'Vitamin C'], ARRAY['Dimakan langsung', 'Jus'], NOW(), NOW()),
(gen_random_uuid(), 'Apel malang segar', 'fruits', 'Indonesia', 57, 0.5, 12.8, 0.4, 2, 5, 9, true, true, true, ARRAY['Serat tinggi', 'Vitamin C'], ARRAY['Dimakan langsung'], NOW(), NOW()),
(gen_random_uuid(), 'Arbei', 'fruits', 'Indonesia', 37, 0.8, 8.3, 0.5, 1.5, 5, 5, true, true, true, ARRAY['Antioksidan', 'Vitamin C tinggi'], ARRAY['Dimakan langsung', 'Selai'], NOW(), NOW()),
(gen_random_uuid(), 'Ayam', 'proteins', 'Indonesia', 302, 18.2, 0, 25, 0, 70, 0, false, false, true, ARRAY['Tinggi protein', 'Sumber zat besi'], ARRAY['Goreng', 'Bakar', 'Sop'], NOW(), NOW()),
(gen_random_uuid(), 'Ayam goreng Kentucky dada', 'proteins', 'Indonesia', 298, 34.2, 0.1, 16.8, 0, 500, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ayam goreng Kentucky paha', 'proteins', 'Indonesia', 286, 32.1, 1.1, 16.1, 0, 500, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ayam goreng paha', 'proteins', 'Indonesia', 287, 31, 1.7, 15.7, 0, 400, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ayam hati segar', 'proteins', 'Indonesia', 261, 27.4, 1.6, 16.1, 0, 70, 0, false, false, true, ARRAY['Tinggi zat besi', 'Vitamin A'], ARRAY['Tumis', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ayam taliwang masakan', 'prepared_dishes', 'Indonesia', 264, 18.2, 2.7, 20.1, 0, 600, 1, false, false, true, ARRAY['Tinggi protein', 'Khas Lombok'], ARRAY['Bakar'], NOW(), NOW()),
(gen_random_uuid(), 'Babat', 'proteins', 'Indonesia', 113, 17.6, 0, 4.2, 0, 50, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Sop', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Bakso', 'proteins', 'Indonesia', 76, 4.1, 9.2, 2.5, 0.5, 600, 1, false, false, true, ARRAY['Protein'], ARRAY['Kuah', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Bakwan', 'snacks', 'Indonesia', 280, 8.2, 39, 10.2, 1, 400, 2, true, true, true, ARRAY['Sumber energi'], ARRAY['Gorengan'], NOW(), NOW()),
(gen_random_uuid(), 'Bayam segar', 'vegetables', 'Indonesia', 36, 3.5, 6.5, 0.5, 2, 5, 0.5, true, true, true, ARRAY['Zat besi tinggi', 'Vitamin A', 'Rendah kalori'], ARRAY['Tumis', 'Sayur bening'], NOW(), NOW()),
(gen_random_uuid(), 'Bayam Merah', 'vegetables', 'Indonesia', 51, 4.6, 10, 0.5, 2.5, 5, 0.5, true, true, true, ARRAY['Zat besi tinggi', 'Antioksidan'], ARRAY['Tumis', 'Sayur'], NOW(), NOW()),
(gen_random_uuid(), 'Bayam rebus', 'vegetables', 'Indonesia', 23, 1.2, 3.7, 0.6, 1.5, 5, 0.5, true, true, true, ARRAY['Rendah kalori', 'Serat tinggi'], ARRAY['Sayur'], NOW(), NOW()),
(gen_random_uuid(), 'Beras Giling', 'grains', 'Indonesia', 360, 6.8, 78.9, 0.7, 0.5, 5, 0, true, true, true, ARRAY['Sumber karbohidrat', 'Energi'], ARRAY['Nasi'], NOW(), NOW()),
(gen_random_uuid(), 'Beras Giling masak (nasi)', 'grains', 'Indonesia', 178, 2.1, 40.6, 0.1, 0.5, 5, 0, true, true, true, ARRAY['Sumber karbohidrat'], ARRAY['Nasi'], NOW(), NOW()),
(gen_random_uuid(), 'Beras Ketan Hitam', 'grains', 'Indonesia', 356, 7, 78, 0.7, 1.5, 5, 0, true, true, true, ARRAY['Antioksidan', 'Serat tinggi'], ARRAY['Ketan', 'Bubur'], NOW(), NOW()),
(gen_random_uuid(), 'Beras Ketan Putih', 'grains', 'Indonesia', 362, 6.7, 79.4, 0.7, 0.5, 5, 0, true, true, true, ARRAY['Sumber energi'], ARRAY['Lemper', 'Ketan'], NOW(), NOW()),
(gen_random_uuid(), 'Beras Merah tumbuk', 'grains', 'Indonesia', 359, 7.5, 77.6, 0.9, 3, 5, 0, true, true, true, ARRAY['Indeks glikemik rendah', 'Serat tinggi', 'Untuk diabetes'], ARRAY['Nasi merah'], NOW(), NOW()),
(gen_random_uuid(), 'Bihun', 'grains', 'Indonesia', 360, 4.7, 82.1, 0.1, 0.5, 5, 0, true, true, true, ARRAY['Sumber karbohidrat'], ARRAY['Goreng', 'Kuah'], NOW(), NOW()),
(gen_random_uuid(), 'Bihun Goreng', 'prepared_dishes', 'Indonesia', 154, 3, 25.5, 4.5, 1, 500, 1, true, true, true, ARRAY['Sumber energi'], ARRAY['Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Biskuit', 'snacks', 'Indonesia', 458, 6.9, 75.1, 14.4, 1, 300, 20, true, true, true, ARRAY['Sumber energi'], ARRAY['Cemilan'], NOW(), NOW()),
(gen_random_uuid(), 'Brokoli', 'vegetables', 'Indonesia', 34, 2.8, 6.6, 0.4, 2.6, 33, 1.7, true, true, true, ARRAY['Vitamin C tinggi', 'Antioksidan', 'Serat tinggi'], ARRAY['Tumis', 'Kukus', 'Salad'], NOW(), NOW()),
(gen_random_uuid(), 'Bubur', 'prepared_dishes', 'Indonesia', 60, 1, 13, 0.2, 0.5, 200, 0, true, true, true, ARRAY['Mudah dicerna'], ARRAY['Sarapan'], NOW(), NOW()),
(gen_random_uuid(), 'Buncis', 'vegetables', 'Indonesia', 35, 2.4, 7.7, 0.2, 2.5, 5, 1, true, true, true, ARRAY['Serat tinggi', 'Rendah kalori'], ARRAY['Tumis', 'Sayur'], NOW(), NOW()),
(gen_random_uuid(), 'Buncis rebus', 'vegetables', 'Indonesia', 30, 2.2, 6.4, 0.2, 2, 5, 1, true, true, true, ARRAY['Rendah kalori', 'Serat tinggi'], ARRAY['Sayur', 'Salad'], NOW(), NOW()),
(gen_random_uuid(), 'Cabai merah segar', 'spices', 'Indonesia', 36, 1, 7.3, 0.3, 1.5, 5, 3, true, true, true, ARRAY['Vitamin C tinggi', 'Meningkatkan metabolisme'], ARRAY['Sambal', 'Bumbu'], NOW(), NOW()),
(gen_random_uuid(), 'Cabai rawit segar', 'spices', 'Indonesia', 120, 4.7, 19.9, 2.4, 2, 10, 3, true, true, true, ARRAY['Capsaicin tinggi', 'Metabolisme'], ARRAY['Sambal'], NOW(), NOW()),
(gen_random_uuid(), 'Cap cai sayur', 'prepared_dishes', 'Indonesia', 97, 5.8, 4.2, 6.3, 2, 400, 2, true, false, true, ARRAY['Sayuran beragam', 'Vitamin'], ARRAY['Tumis'], NOW(), NOW()),
(gen_random_uuid(), 'Coklat bubuk', 'other', 'Indonesia', 311, 8, 48.9, 4, 3, 50, 5, true, true, true, ARRAY['Antioksidan', 'Mood booster'], ARRAY['Minuman', 'Kue'], NOW(), NOW()),
(gen_random_uuid(), 'Corned Beef', 'proteins', 'Indonesia', 241, 16, 0, 25, 0, 800, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Sandwich', 'Tumis'], NOW(), NOW()),
(gen_random_uuid(), 'Daging Ayam', 'proteins', 'Indonesia', 302, 18.2, 0, 25, 0, 70, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Goreng', 'Bakar', 'Sop'], NOW(), NOW()),
(gen_random_uuid(), 'Daging Sapi', 'proteins', 'Indonesia', 207, 18.8, 0, 14, 0, 50, 0, false, false, true, ARRAY['Tinggi protein', 'Zat besi'], ARRAY['Rendang', 'Sate', 'Steak'], NOW(), NOW()),
(gen_random_uuid(), 'Daging Kambing', 'proteins', 'Indonesia', 154, 16.6, 0, 9.2, 0, 70, 0, false, false, true, ARRAY['Tinggi protein'], ARRAY['Sate', 'Gulai', 'Tongseng'], NOW(), NOW()),
(gen_random_uuid(), 'Daun Bayam', 'vegetables', 'Indonesia', 36, 3.5, 6.5, 0.5, 2, 5, 0.5, true, true, true, ARRAY['Zat besi tinggi', 'Vitamin A'], ARRAY['Tumis', 'Sayur bening'], NOW(), NOW()),
(gen_random_uuid(), 'Daun Kangkung', 'vegetables', 'Indonesia', 29, 3, 5.4, 0.3, 2, 5, 0.5, true, true, true, ARRAY['Zat besi', 'Rendah kalori'], ARRAY['Tumis', 'Plecing'], NOW(), NOW()),
(gen_random_uuid(), 'Daun Kelor', 'vegetables', 'Indonesia', 82, 6.7, 14.3, 1.7, 3, 10, 0.5, true, true, true, ARRAY['Superfood', 'Vitamin tinggi', 'Protein nabati'], ARRAY['Sayur bening', 'Tumis'], NOW(), NOW()),
(gen_random_uuid(), 'Daun Singkong', 'vegetables', 'Indonesia', 73, 6.8, 13, 1.2, 2.5, 10, 1, true, true, true, ARRAY['Protein nabati', 'Vitamin C'], ARRAY['Tumis', 'Gulai'], NOW(), NOW()),
(gen_random_uuid(), 'Daun Katuk', 'vegetables', 'Indonesia', 59, 4.8, 11, 1, 2, 5, 0.5, true, true, true, ARRAY['ASI booster', 'Zat besi'], ARRAY['Sayur', 'Tumis'], NOW(), NOW()),
(gen_random_uuid(), 'Durian', 'fruits', 'Indonesia', 134, 2.5, 28, 3, 3, 5, 15, true, true, true, ARRAY['Energi tinggi', 'Potasium'], ARRAY['Dimakan langsung', 'Es'], NOW(), NOW()),
(gen_random_uuid(), 'Duku', 'fruits', 'Indonesia', 63, 1, 16.1, 0.2, 1, 5, 12, true, true, true, ARRAY['Vitamin C', 'Serat'], ARRAY['Dimakan langsung'], NOW(), NOW()),
(gen_random_uuid(), 'Gado-gado', 'prepared_dishes', 'Indonesia', 137, 6.1, 21, 3.2, 3, 400, 5, true, false, true, ARRAY['Sayuran beragam', 'Protein nabati'], ARRAY['Salad Indonesia'], NOW(), NOW()),
(gen_random_uuid(), 'Gudeg', 'prepared_dishes', 'Indonesia', 53, 1.6, 8.8, 1.6, 2, 300, 10, true, true, true, ARRAY['Khas Yogyakarta', 'Serat'], ARRAY['Lauk'], NOW(), NOW()),
(gen_random_uuid(), 'Gula Aren', 'other', 'Indonesia', 368, 0, 95, 0, 0, 10, 90, true, true, true, ARRAY['Indeks glikemik rendah'], ARRAY['Pemanis'], NOW(), NOW()),
(gen_random_uuid(), 'Gula Kelapa', 'other', 'Indonesia', 386, 3, 76, 10, 0, 10, 70, true, true, true, ARRAY['Mineral', 'Indeks glikemik rendah'], ARRAY['Pemanis'], NOW(), NOW()),
(gen_random_uuid(), 'Gula putih', 'other', 'Indonesia', 394, 0, 94, 0, 0, 5, 94, true, true, true, ARRAY['Sumber energi cepat'], ARRAY['Pemanis'], NOW(), NOW()),
(gen_random_uuid(), 'Hati Sapi', 'proteins', 'Indonesia', 136, 19.7, 6, 3.2, 0, 70, 0, false, false, true, ARRAY['Zat besi tinggi', 'Vitamin A', 'Vitamin B12'], ARRAY['Tumis', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Bandeng', 'proteins', 'Indonesia', 129, 20, 0, 4.8, 0, 60, 0, false, false, true, ARRAY['Omega-3', 'Protein tinggi'], ARRAY['Presto', 'Bakar', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Bawal', 'proteins', 'Indonesia', 96, 19, 0, 1.7, 0, 50, 0, false, false, true, ARRAY['Rendah lemak', 'Protein tinggi'], ARRAY['Goreng', 'Bakar'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Gabus', 'proteins', 'Indonesia', 74, 25.2, 0, 1.7, 0, 50, 0, false, false, true, ARRAY['Albumin tinggi', 'Penyembuhan luka'], ARRAY['Goreng', 'Sup'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Kembung', 'proteins', 'Indonesia', 103, 22, 0, 1, 0, 50, 0, false, false, true, ARRAY['Omega-3', 'Protein tinggi', 'Terjangkau'], ARRAY['Goreng', 'Pindang'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Lele', 'proteins', 'Indonesia', 112, 20, 0, 3, 0, 50, 0, false, false, true, ARRAY['Protein tinggi', 'Terjangkau'], ARRAY['Goreng', 'Pecel'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Mas', 'proteins', 'Indonesia', 86, 16, 0, 2, 0, 50, 0, false, false, true, ARRAY['Protein tinggi'], ARRAY['Pepes', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Mujair', 'proteins', 'Indonesia', 89, 18.7, 0, 1, 0, 50, 0, false, false, true, ARRAY['Protein tinggi', 'Rendah lemak'], ARRAY['Goreng', 'Bakar'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Nila', 'proteins', 'Indonesia', 96, 20, 0, 1.7, 0, 50, 0, false, false, true, ARRAY['Protein tinggi', 'Rendah lemak'], ARRAY['Goreng', 'Bakar', 'Pepes'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Patin', 'proteins', 'Indonesia', 132, 17, 1.1, 6.6, 0, 50, 0, false, false, true, ARRAY['Omega-3'], ARRAY['Bakar', 'Gulai'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Salmon', 'proteins', 'Indonesia', 208, 20, 0, 13, 0, 60, 0, false, false, true, ARRAY['Omega-3 tinggi', 'Vitamin D'], ARRAY['Panggang', 'Sashimi'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Sarden', 'proteins', 'Indonesia', 109, 19.9, 3.4, 1.8, 0, 300, 0, false, false, true, ARRAY['Omega-3', 'Kalsium'], ARRAY['Kaleng', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Tuna', 'proteins', 'Indonesia', 132, 29, 0, 1, 0, 40, 0, false, false, true, ARRAY['Protein sangat tinggi', 'Omega-3'], ARRAY['Steak', 'Sashimi'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Teri', 'proteins', 'Indonesia', 170, 33.4, 0, 3, 0, 800, 0, false, false, true, ARRAY['Kalsium tinggi', 'Protein'], ARRAY['Goreng', 'Sambal'], NOW(), NOW()),
(gen_random_uuid(), 'Ikan Tongkol', 'proteins', 'Indonesia', 100, 13.7, 8, 1.5, 0, 50, 0, false, false, true, ARRAY['Protein tinggi', 'Terjangkau'], ARRAY['Goreng', 'Balado'], NOW(), NOW()),
(gen_random_uuid(), 'Jagung Kuning', 'grains', 'Indonesia', 140, 4.7, 33.1, 1.3, 2, 5, 3, true, true, true, ARRAY['Serat tinggi', 'Vitamin A'], ARRAY['Rebus', 'Bakar'], NOW(), NOW()),
(gen_random_uuid(), 'Jagung Rebus', 'grains', 'Indonesia', 175, 1.8, 35, 1.8, 2.5, 5, 4, true, true, true, ARRAY['Serat tinggi', 'Energi'], ARRAY['Cemilan'], NOW(), NOW()),
(gen_random_uuid(), 'Jahe', 'spices', 'Indonesia', 51, 1.5, 10.1, 1, 2, 10, 1, true, true, true, ARRAY['Anti mual', 'Anti inflamasi', 'Pencernaan'], ARRAY['Minuman', 'Bumbu'], NOW(), NOW()),
(gen_random_uuid(), 'Jambu Biji', 'fruits', 'Indonesia', 49, 0.9, 12.2, 0.3, 5, 5, 9, true, true, true, ARRAY['Vitamin C sangat tinggi', 'Serat tinggi'], ARRAY['Dimakan langsung', 'Jus'], NOW(), NOW()),
(gen_random_uuid(), 'Jamur tiram', 'vegetables', 'Indonesia', 30, 1.9, 5.5, 0.1, 2, 5, 0.5, true, true, true, ARRAY['Protein nabati', 'Rendah kalori'], ARRAY['Tumis', 'Goreng tepung'], NOW(), NOW()),
(gen_random_uuid(), 'Jengkol', 'vegetables', 'Indonesia', 192, 5.4, 40.7, 0.3, 3, 10, 1, true, true, true, ARRAY['Serat tinggi', 'Protein nabati'], ARRAY['Semur', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Jeruk Manis', 'fruits', 'Indonesia', 45, 0.9, 11.2, 0.2, 2, 5, 9, true, true, true, ARRAY['Vitamin C tinggi', 'Antioksidan'], ARRAY['Dimakan langsung', 'Jus'], NOW(), NOW()),
(gen_random_uuid(), 'Kacang Hijau', 'grains', 'Indonesia', 323, 22.9, 56.8, 1.5, 5, 5, 3, true, true, true, ARRAY['Protein tinggi', 'Serat tinggi', 'Rendah lemak'], ARRAY['Bubur', 'Onde-onde'], NOW(), NOW()),
(gen_random_uuid(), 'Kacang Kedelai', 'proteins', 'Indonesia', 381, 40.4, 24.9, 16.7, 6, 5, 2, true, true, true, ARRAY['Protein sangat tinggi', 'Isoflavon'], ARRAY['Tempe', 'Tahu', 'Susu kedelai'], NOW(), NOW()),
(gen_random_uuid(), 'Kacang Merah', 'grains', 'Indonesia', 336, 23.1, 59.5, 1.7, 6, 5, 2, true, true, true, ARRAY['Protein tinggi', 'Serat tinggi', 'Zat besi'], ARRAY['Sup', 'Es'], NOW(), NOW()),
(gen_random_uuid(), 'Kacang Panjang', 'vegetables', 'Indonesia', 44, 2.7, 7.8, 0.3, 2.5, 5, 1, true, true, true, ARRAY['Serat tinggi', 'Rendah kalori'], ARRAY['Tumis', 'Lalapan'], NOW(), NOW()),
(gen_random_uuid(), 'Kacang Tanah', 'proteins', 'Indonesia', 525, 27.9, 17.4, 42.7, 3, 10, 2, true, true, true, ARRAY['Protein tinggi', 'Lemak sehat'], ARRAY['Goreng', 'Bumbu'], NOW(), NOW()),
(gen_random_uuid(), 'Kangkung', 'vegetables', 'Indonesia', 29, 3, 5.4, 0.3, 2, 5, 0.5, true, true, true, ARRAY['Zat besi', 'Rendah kalori', 'Vitamin A'], ARRAY['Tumis', 'Plecing'], NOW(), NOW()),
(gen_random_uuid(), 'Kelapa Muda', 'fruits', 'Indonesia', 68, 1, 14, 0.9, 1, 5, 2, true, true, true, ARRAY['Elektrolit alami', 'Hidrasi'], ARRAY['Es kelapa', 'Dimakan langsung'], NOW(), NOW()),
(gen_random_uuid(), 'Kelapa Tua', 'fruits', 'Indonesia', 359, 3.4, 14, 34.7, 3, 10, 3, true, true, true, ARRAY['Lemak sehat', 'Serat'], ARRAY['Santan', 'Serundeng'], NOW(), NOW()),
(gen_random_uuid(), 'Kemiri', 'spices', 'Indonesia', 636, 19, 8, 63, 3, 5, 1, true, true, true, ARRAY['Lemak sehat', 'Bumbu dasar'], ARRAY['Bumbu masakan'], NOW(), NOW()),
(gen_random_uuid(), 'Kentang', 'grains', 'Indonesia', 83, 2, 19.1, 0.1, 2, 5, 1, true, true, true, ARRAY['Karbohidrat kompleks', 'Vitamin C'], ARRAY['Goreng', 'Rebus', 'Sup'], NOW(), NOW()),
(gen_random_uuid(), 'Kepiting', 'proteins', 'Indonesia', 151, 13.8, 14.1, 3.8, 0, 300, 0, false, false, true, ARRAY['Protein tinggi', 'Omega-3'], ARRAY['Saus padang', 'Kukus'], NOW(), NOW()),
(gen_random_uuid(), 'Kerang', 'proteins', 'Indonesia', 59, 18, 3.6, 1.1, 0, 300, 0, false, false, true, ARRAY['Protein tinggi', 'Zat besi'], ARRAY['Saus padang', 'Tumis'], NOW(), NOW()),
(gen_random_uuid(), 'Kerupuk Udang', 'snacks', 'Indonesia', 340, 30, 52, 30, 0.5, 800, 1, false, false, true, ARRAY['Protein'], ARRAY['Pelengkap makan'], NOW(), NOW()),
(gen_random_uuid(), 'Ketimun', 'vegetables', 'Indonesia', 12, 0.7, 2.7, 0.1, 0.5, 5, 1, true, true, true, ARRAY['Hidrasi', 'Rendah kalori'], ARRAY['Lalapan', 'Acar', 'Salad'], NOW(), NOW()),
(gen_random_uuid(), 'Ketupat', 'grains', 'Indonesia', 109, 2.6, 18.6, 2.6, 0.5, 5, 0, true, true, true, ARRAY['Sumber karbohidrat'], ARRAY['Lebaran', 'Ketupat sayur'], NOW(), NOW()),
(gen_random_uuid(), 'Kol/Kubis', 'vegetables', 'Indonesia', 25, 1.3, 5.8, 0.1, 2, 18, 3, true, true, true, ARRAY['Vitamin C', 'Serat', 'Rendah kalori'], ARRAY['Tumis', 'Salad', 'Asinan'], NOW(), NOW()),
(gen_random_uuid(), 'Kunyit', 'spices', 'Indonesia', 354, 9.7, 64, 9.9, 21, 38, 3, true, true, true, ARRAY['Anti inflamasi', 'Antioksidan', 'Kesehatan hati'], ARRAY['Bumbu', 'Jamu'], NOW(), NOW()),
(gen_random_uuid(), 'Labu Kuning/Waluh', 'vegetables', 'Indonesia', 26, 1, 6.5, 0.1, 0.5, 1, 2.5, true, true, true, ARRAY['Vitamin A tinggi', 'Rendah kalori'], ARRAY['Kolak', 'Sayur', 'Kue'], NOW(), NOW()),
(gen_random_uuid(), 'Labu Siam', 'vegetables', 'Indonesia', 20, 0.8, 4.5, 0.1, 1.5, 2, 2, true, true, true, ARRAY['Rendah kalori', 'Serat'], ARRAY['Sayur', 'Tumis'], NOW(), NOW()),
(gen_random_uuid(), 'Lengkuas', 'spices', 'Indonesia', 22, 1, 4.7, 0.3, 2, 5, 0.5, true, true, true, ARRAY['Anti inflamasi', 'Bumbu dasar'], ARRAY['Bumbu masakan'], NOW(), NOW()),
(gen_random_uuid(), 'Lontong', 'grains', 'Indonesia', 109, 2.6, 18.6, 2.6, 0.5, 5, 0, true, true, true, ARRAY['Sumber karbohidrat'], ARRAY['Sayur', 'Sate'], NOW(), NOW()),
(gen_random_uuid(), 'Mangga', 'fruits', 'Indonesia', 60, 0.8, 15, 0.4, 1.5, 1, 14, true, true, true, ARRAY['Vitamin C', 'Vitamin A', 'Serat'], ARRAY['Dimakan langsung', 'Jus', 'Rujak'], NOW(), NOW()),
(gen_random_uuid(), 'Melon', 'fruits', 'Indonesia', 34, 0.8, 8.2, 0.2, 0.9, 16, 8, true, true, true, ARRAY['Hidrasi', 'Vitamin C'], ARRAY['Dimakan langsung', 'Es'], NOW(), NOW()),
(gen_random_uuid(), 'Mie Instan', 'grains', 'Indonesia', 473, 9.3, 62.6, 20.4, 2, 1500, 3, true, true, true, ARRAY['Praktis', 'Sumber energi'], ARRAY['Goreng', 'Kuah'], NOW(), NOW()),
(gen_random_uuid(), 'Nangka', 'fruits', 'Indonesia', 94, 1.5, 23.2, 0.6, 1.5, 3, 19, true, true, true, ARRAY['Vitamin C', 'Serat', 'Energi'], ARRAY['Dimakan langsung', 'Kolak'], NOW(), NOW()),
(gen_random_uuid(), 'Nasi Goreng', 'prepared_dishes', 'Indonesia', 185, 4.1, 26.3, 7.2, 1, 600, 1, false, false, true, ARRAY['Sumber energi', 'Praktis'], ARRAY['Sarapan', 'Makan siang'], NOW(), NOW()),
(gen_random_uuid(), 'Nasi Putih', 'grains', 'Indonesia', 178, 2.1, 40.6, 0.1, 0.5, 5, 0, true, true, true, ARRAY['Sumber karbohidrat utama'], ARRAY['Makanan pokok'], NOW(), NOW()),
(gen_random_uuid(), 'Nasi Uduk', 'prepared_dishes', 'Indonesia', 210, 4, 28, 9, 1, 300, 1, true, true, true, ARRAY['Sumber energi'], ARRAY['Sarapan'], NOW(), NOW()),
(gen_random_uuid(), 'Oncom', 'proteins', 'Indonesia', 187, 13, 26.9, 6, 4, 10, 0, true, true, true, ARRAY['Protein nabati', 'Probiotik', 'Khas Sunda'], ARRAY['Goreng', 'Tumis'], NOW(), NOW()),
(gen_random_uuid(), 'Papaya/Pepaya', 'fruits', 'Indonesia', 39, 0.6, 9.8, 0.1, 1.8, 3, 6, true, true, true, ARRAY['Enzim papain', 'Vitamin C', 'Pencernaan'], ARRAY['Dimakan langsung', 'Jus'], NOW(), NOW()),
(gen_random_uuid(), 'Pare', 'vegetables', 'Indonesia', 17, 1, 3.7, 0.2, 2.8, 5, 0.5, true, true, true, ARRAY['Menurunkan gula darah', 'Untuk diabetes', 'Detoksifikasi'], ARRAY['Tumis', 'Lalapan'], NOW(), NOW()),
(gen_random_uuid(), 'Pecel', 'prepared_dishes', 'Indonesia', 180, 8, 24, 6, 5, 400, 3, true, false, true, ARRAY['Sayuran beragam', 'Protein kacang'], ARRAY['Makan siang'], NOW(), NOW()),
(gen_random_uuid(), 'Pepaya muda/mentah', 'vegetables', 'Indonesia', 26, 0.5, 6.3, 0.1, 2, 3, 2, true, true, true, ARRAY['Enzim papain', 'Rendah kalori'], ARRAY['Sayur', 'Sup'], NOW(), NOW()),
(gen_random_uuid(), 'Pete/Petai', 'vegetables', 'Indonesia', 128, 12, 26, 0.8, 3, 10, 1, true, true, true, ARRAY['Protein nabati', 'Serat tinggi'], ARRAY['Sambal', 'Tumis'], NOW(), NOW()),
(gen_random_uuid(), 'Pisang Ambon', 'fruits', 'Indonesia', 89, 1.1, 22.8, 0.3, 2.6, 1, 12, true, true, true, ARRAY['Potasium tinggi', 'Energi cepat', 'Pencernaan'], ARRAY['Dimakan langsung'], NOW(), NOW()),
(gen_random_uuid(), 'Pisang Goreng', 'snacks', 'Indonesia', 290, 2.5, 38, 14.5, 2, 200, 20, true, true, true, ARRAY['Sumber energi'], ARRAY['Cemilan'], NOW(), NOW()),
(gen_random_uuid(), 'Pisang Kepok', 'fruits', 'Indonesia', 122, 1.6, 32, 0.2, 2.3, 1, 15, true, true, true, ARRAY['Energi', 'Serat'], ARRAY['Goreng', 'Kolak'], NOW(), NOW()),
(gen_random_uuid(), 'Rambutan', 'fruits', 'Indonesia', 82, 0.9, 20.9, 0.2, 0.9, 11, 18, true, true, true, ARRAY['Vitamin C', 'Hidrasi'], ARRAY['Dimakan langsung'], NOW(), NOW()),
(gen_random_uuid(), 'Rawon', 'prepared_dishes', 'Indonesia', 91, 8.2, 3.4, 5.2, 1, 500, 1, false, false, true, ARRAY['Protein daging', 'Khas Jawa Timur'], ARRAY['Makan siang'], NOW(), NOW()),
(gen_random_uuid(), 'Rendang', 'prepared_dishes', 'Indonesia', 468, 22.6, 9.3, 38.2, 2, 450, 2, false, false, true, ARRAY['Protein tinggi', 'Rempah lengkap', 'Tahan lama'], ARRAY['Lauk'], NOW(), NOW()),
(gen_random_uuid(), 'Salak', 'fruits', 'Indonesia', 82, 0.4, 21.3, 0.4, 2.8, 3, 13, true, true, true, ARRAY['Serat tinggi', 'Vitamin C'], ARRAY['Dimakan langsung'], NOW(), NOW()),
(gen_random_uuid(), 'Sambal', 'spices', 'Indonesia', 88, 2.5, 16.4, 1.5, 2, 800, 5, true, true, true, ARRAY['Vitamin C', 'Metabolisme'], ARRAY['Pelengkap'], NOW(), NOW()),
(gen_random_uuid(), 'Santan', 'other', 'Indonesia', 230, 2.3, 6, 24, 0, 10, 3, true, true, true, ARRAY['Lemak sehat', 'Energi'], ARRAY['Kuah', 'Kue'], NOW(), NOW()),
(gen_random_uuid(), 'Sate Ayam', 'prepared_dishes', 'Indonesia', 239, 20.7, 8.1, 13.7, 0.5, 500, 4, false, false, true, ARRAY['Protein tinggi', 'Khas Indonesia'], ARRAY['Makan malam'], NOW(), NOW()),
(gen_random_uuid(), 'Sate Kambing', 'prepared_dishes', 'Indonesia', 235, 19.5, 3, 16.3, 0, 400, 1, false, false, true, ARRAY['Protein tinggi'], ARRAY['Makan malam'], NOW(), NOW()),
(gen_random_uuid(), 'Sawi Hijau', 'vegetables', 'Indonesia', 12, 1.5, 1.6, 0.2, 1.2, 20, 1, true, true, true, ARRAY['Vitamin A', 'Vitamin C', 'Rendah kalori'], ARRAY['Tumis', 'Kuah'], NOW(), NOW()),
(gen_random_uuid(), 'Sawi Putih', 'vegetables', 'Indonesia', 13, 1.2, 2.2, 0.2, 1, 65, 1.2, true, true, true, ARRAY['Rendah kalori', 'Vitamin C'], ARRAY['Tumis', 'Kuah'], NOW(), NOW()),
(gen_random_uuid(), 'Sayur Asem', 'prepared_dishes', 'Indonesia', 35, 1.2, 6.8, 0.5, 2, 400, 3, true, true, true, ARRAY['Sayuran beragam', 'Segar'], ARRAY['Kuah'], NOW(), NOW()),
(gen_random_uuid(), 'Sayur Lodeh', 'prepared_dishes', 'Indonesia', 80, 2.5, 8, 4.5, 2, 400, 2, true, true, true, ARRAY['Sayuran beragam', 'Santan'], ARRAY['Kuah'], NOW(), NOW()),
(gen_random_uuid(), 'Sayur Sop', 'prepared_dishes', 'Indonesia', 55, 3.2, 7.5, 1.5, 2, 400, 2, false, false, true, ARRAY['Sayuran beragam', 'Rendah kalori'], ARRAY['Kuah'], NOW(), NOW()),
(gen_random_uuid(), 'Semangka', 'fruits', 'Indonesia', 30, 0.6, 7.6, 0.2, 0.4, 1, 6, true, true, true, ARRAY['Hidrasi tinggi', 'Vitamin C', 'Antioksidan'], ARRAY['Dimakan langsung', 'Jus'], NOW(), NOW()),
(gen_random_uuid(), 'Sereh/Serai', 'spices', 'Indonesia', 99, 1.8, 25.3, 0.5, 2, 6, 0, true, true, true, ARRAY['Aromaterapi', 'Anti bakteri', 'Bumbu'], ARRAY['Bumbu masakan', 'Minuman'], NOW(), NOW()),
(gen_random_uuid(), 'Singkong', 'grains', 'Indonesia', 154, 1, 36.8, 0.3, 2, 10, 2, true, true, true, ARRAY['Karbohidrat', 'Energi', 'Alternatif nasi'], ARRAY['Goreng', 'Rebus', 'Tape'], NOW(), NOW()),
(gen_random_uuid(), 'Sirsak', 'fruits', 'Indonesia', 66, 1, 16.8, 0.3, 3.3, 14, 14, true, true, true, ARRAY['Vitamin C', 'Antioksidan'], ARRAY['Dimakan langsung', 'Jus'], NOW(), NOW()),
(gen_random_uuid(), 'Soto Ayam', 'prepared_dishes', 'Indonesia', 89, 7.5, 5.6, 4.4, 0.5, 500, 1, false, false, true, ARRAY['Protein', 'Rempah'], ARRAY['Sarapan', 'Makan siang'], NOW(), NOW()),
(gen_random_uuid(), 'Susu Sapi Murni', 'dairy', 'Indonesia', 61, 3.2, 4.8, 3.3, 0, 43, 5, true, false, true, ARRAY['Kalsium tinggi', 'Protein', 'Vitamin D'], ARRAY['Minuman'], NOW(), NOW()),
(gen_random_uuid(), 'Tahu', 'proteins', 'Indonesia', 76, 8.1, 1.9, 4.2, 0.3, 7, 0.5, true, true, true, ARRAY['Protein nabati', 'Kalsium', 'Rendah kalori'], ARRAY['Goreng', 'Bacem', 'Sup'], NOW(), NOW()),
(gen_random_uuid(), 'Tahu Goreng', 'proteins', 'Indonesia', 270, 17.2, 10.2, 18.8, 0.5, 200, 1, true, true, true, ARRAY['Protein nabati'], ARRAY['Lauk'], NOW(), NOW()),
(gen_random_uuid(), 'Talas', 'grains', 'Indonesia', 98, 1.6, 20.9, 0.7, 4.1, 11, 0.5, true, true, true, ARRAY['Serat tinggi', 'Alternatif karbohidrat'], ARRAY['Rebus', 'Goreng', 'Kolak'], NOW(), NOW()),
(gen_random_uuid(), 'Tape Singkong', 'snacks', 'Indonesia', 173, 0.5, 42.5, 0.1, 0.5, 5, 15, true, true, true, ARRAY['Probiotik', 'Fermentasi'], ARRAY['Cemilan'], NOW(), NOW()),
(gen_random_uuid(), 'Tauge', 'vegetables', 'Indonesia', 31, 3.2, 5.9, 0.2, 1.8, 6, 4.1, true, true, true, ARRAY['Protein nabati', 'Vitamin C'], ARRAY['Tumis', 'Lalapan'], NOW(), NOW()),
(gen_random_uuid(), 'Telur Ayam', 'proteins', 'Indonesia', 155, 12.6, 1.1, 11, 0, 124, 1.1, true, false, true, ARRAY['Protein lengkap', 'Vitamin B12', 'Kolin'], ARRAY['Goreng', 'Rebus', 'Orak-arik'], NOW(), NOW()),
(gen_random_uuid(), 'Telur Asin', 'proteins', 'Indonesia', 184, 13.5, 1.5, 13.6, 0, 1500, 1, true, false, true, ARRAY['Protein', 'Rasa kuat'], ARRAY['Lauk', 'Pelengkap'], NOW(), NOW()),
(gen_random_uuid(), 'Telur Bebek', 'proteins', 'Indonesia', 185, 13, 1.5, 14, 0, 150, 1, true, false, true, ARRAY['Protein tinggi', 'Lemak lebih tinggi'], ARRAY['Goreng', 'Balado'], NOW(), NOW()),
(gen_random_uuid(), 'Telur Puyuh', 'proteins', 'Indonesia', 158, 13.1, 0.4, 11, 0, 141, 0.4, true, false, true, ARRAY['Protein tinggi'], ARRAY['Rebus', 'Sate'], NOW(), NOW()),
(gen_random_uuid(), 'Tempe', 'proteins', 'Indonesia', 192, 18.5, 7.6, 10.8, 1.4, 9, 0, true, true, true, ARRAY['Protein sangat tinggi', 'Probiotik', 'Serat', 'Murah'], ARRAY['Goreng', 'Bacem', 'Mendoan'], NOW(), NOW()),
(gen_random_uuid(), 'Tempe Goreng', 'proteins', 'Indonesia', 338, 21.5, 11.5, 24, 2, 300, 1, true, true, true, ARRAY['Protein tinggi'], ARRAY['Lauk'], NOW(), NOW()),
(gen_random_uuid(), 'Terasi', 'spices', 'Indonesia', 237, 30.4, 16.4, 3.4, 0, 2500, 0, false, false, true, ARRAY['Protein', 'Bumbu kuat'], ARRAY['Sambal', 'Bumbu'], NOW(), NOW()),
(gen_random_uuid(), 'Terong', 'vegetables', 'Indonesia', 25, 1, 5.9, 0.2, 3, 2, 3.5, true, true, true, ARRAY['Rendah kalori', 'Serat', 'Antioksidan'], ARRAY['Tumis', 'Balado', 'Terong bakar'], NOW(), NOW()),
(gen_random_uuid(), 'Toge/Tauge', 'vegetables', 'Indonesia', 31, 3.2, 5.9, 0.2, 1.8, 6, 4.1, true, true, true, ARRAY['Protein nabati', 'Vitamin C'], ARRAY['Tumis', 'Lalapan'], NOW(), NOW()),
(gen_random_uuid(), 'Tomat', 'vegetables', 'Indonesia', 18, 0.9, 3.9, 0.2, 1.2, 5, 2.6, true, true, true, ARRAY['Likopen', 'Vitamin C', 'Antioksidan'], ARRAY['Salad', 'Sambal', 'Sup'], NOW(), NOW()),
(gen_random_uuid(), 'Tongkol Balado', 'prepared_dishes', 'Indonesia', 165, 20.5, 5.8, 6.8, 1, 600, 2, false, false, true, ARRAY['Protein tinggi', 'Omega-3'], ARRAY['Lauk'], NOW(), NOW()),
(gen_random_uuid(), 'Ubi Jalar Kuning', 'grains', 'Indonesia', 86, 1.6, 20.1, 0.1, 3, 55, 4.2, true, true, true, ARRAY['Vitamin A tinggi', 'Serat', 'Indeks glikemik rendah'], ARRAY['Rebus', 'Goreng'], NOW(), NOW()),
(gen_random_uuid(), 'Ubi Jalar Merah/Ungu', 'grains', 'Indonesia', 90, 1.8, 20.7, 0.1, 3, 55, 4.5, true, true, true, ARRAY['Antioksidan tinggi', 'Vitamin A', 'Serat'], ARRAY['Rebus', 'Goreng', 'Kolak'], NOW(), NOW()),
(gen_random_uuid(), 'Udang', 'proteins', 'Indonesia', 99, 20.9, 0.2, 1.1, 0, 111, 0, false, false, true, ARRAY['Protein tinggi', 'Rendah lemak', 'Selenium'], ARRAY['Goreng', 'Tumis', 'Pepes'], NOW(), NOW()),
(gen_random_uuid(), 'Wortel', 'vegetables', 'Indonesia', 41, 0.9, 9.6, 0.2, 2.8, 69, 4.7, true, true, true, ARRAY['Vitamin A sangat tinggi', 'Kesehatan mata', 'Antioksidan'], ARRAY['Sup', 'Tumis', 'Jus'], NOW(), NOW())

ON CONFLICT (name) DO UPDATE SET
  calories = EXCLUDED.calories,
  protein_g = EXCLUDED.protein_g,
  carbs_g = EXCLUDED.carbs_g,
  fat_g = EXCLUDED.fat_g,
  updated_at = NOW();

-- Show count of inserted foods
SELECT COUNT(*) as total_foods FROM local_foods;
